### ISSUE TITLE
Remove namespaces

### ISSUE THREAD

**Issue by ktbolt** [StanfordCBCL/svZeroDPlus#48]
Namespaces are not really needed to differentiate names from other libraries and such so I would like to remove them.

**Comment by menon-karthik** [comment]
@ktbolt I sort of like namespaces because they make the code easier to navigate sometimes (i.e. you know where to look for a class without using `grep` on the whole code). I don't have strong preferences, so I'm ok with not having them if you feel strongly.

I was also wondering - we currently don't have a uniform system for file names. Some [have underscores](https://github.com/StanfordCBCL/svZeroDPlus/blob/master/src/solve/csv_writer.cpp), some are [in lower case](https://github.com/StanfordCBCL/svZeroDPlus/blob/master/src/optimize/calibrate.cpp) and the rest are in camel case. What do you think we should stick to (it doesn't seem consistent in svFSIplus either)?

**Comment by ktbolt** [comment]
@menon-karthik To me the namespaces are just added noise that don't really provide an important function. This is a small code and easy to navigate I think.

The file naming convention is
- camel case for C++ classes
- snake case for everything else, underscores for readability
